test-2

name: Insecure Context Injection Mitigation
 
on: 
  pull_request_target: 
    branches: 
      - main
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Make shell.sh executable
        run: echo "test 1"
      - name: Run shell.sh
        run: echo "Test 2"
      - name: Check exit code of shell.sh
        run: echo "shell.sh exit code: $?"
      - name: Use environment variables  
        run: | 
          echo "Insercure context"
          echo "Building branch for : ${{ github.event.pull_request.head.ref }}"
