test

name: Insecure Context Injection Mitigation
 
on: 
  pull_request_target: 
    branches: 
      - main

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Make shell.sh executable
        run: chmod +x shell.sh
      - name: Run shell.sh
        run: ./shell.sh
      - name: Check exit code of shell.sh
        run: echo "shell.sh exit code: $?"
      - name: Use environment variables  
        run: |  
          echo "Using environment variables"
          echo "Building the project for branch: $BRANCH_NAME"
